#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace NB_Tags
{
	namespace Abilities
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefaultAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability02);
	}

	namespace Animation
	{
		// Sequence
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpecialIdle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BattleIdle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(JumpStart);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(OnLand);
		
		// Blend Space
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveBlendSpace);
		//UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability02);
		
		// Montage
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefaultAttack01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefaultAttack02);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefaultAttack03);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability02);
	}
}
